### ISSUE TITLE
Which i need to compile?

### ISSUE THREAD

**Issue by inukaze** [loganmc10/m64p-netplay-server#4]
```
[ inukaze | 21-09-2020 | 04:23 am ]
[tmp]$ git clone https://github.com/loganmc10/m64p-netplay-server.git
Cloning into 'm64p-netplay-server'...
remote: Enumerating objects: 92, done.
remote: Counting objects: 100% (92/92), done.
remote: Compressing objects: 100% (66/66), done.
remote: Total 578 (delta 56), reused 51 (delta 26), pack-reused 486
Receiving objects: 100% (578/578), 153.64 KiB | 205.00 KiB/s, done.
Resolving deltas: 100% (385/385), done.

[ inukaze | 21-09-2020 | 04:24 am ]
[tmp]$ cd m64p-netplay-server

[ inukaze | 21-09-2020 | 04:24 am ]
[m64p-netplay-server]$ mkdir build

[ inukaze | 21-09-2020 | 04:24 am ]
[m64p-netplay-server]$ cd build

[ inukaze | 21-09-2020 | 04:24 am ]
[build]$ qmake ..
Project MESSAGE: Warning: unknown QT: websockets

[ inukaze | 21-09-2020 | 04:24 am ]
[build]$ 
```

**Comment by loganmc10** [comment]
Yes you'll need to install the qt5 websockets development package for your distro. Each distro names it slightly different.

For example (you'd need the -dev version of these packages):
Fedora: qt5-qtwebsockets
Arch: qt5-websockets
Ubuntu: libqt5websockets5

**Comment by inukaze** [comment]
i know on the distributions the package name normally is diferent and that is a thing i never saw sense but well, i am trying to solve this dependency.

**Comment by inukaze** [comment]
i notice i must use "qmake-qt5" instead "qmake" because if i use "qmake" this use default qt4, and with the another the qt5 and with that not show that message, well if you read the another issue, you can notice the compilation try to complete but on some point failed xD
