### ISSUE TITLE
Dunnos

### ISSUE THREAD

**Issue by inukaze** [loganmc10/m64p-netplay-server#5]
Hi there again, can you tell me which software i need for compile the server under Windows 7 (32 Bits / 64 Bits) ?

and the another question is why the server don't have a prebuilt release for windows ?

**Comment by loganmc10** [comment]
The server is hosted in the cloud, there are 3 regions: US West, US East, and Europe.

Self hosting is possible, but isn't officially supported (you're on your own)

**Comment by inukaze** [comment]
Is not possible use the server only on Intranet without Internet?

**Comment by loganmc10** [comment]
It's possible, but I'm saying you'll have to figure it out on your own

**Comment by inukaze** [comment]
Well i am not Windows user, because of that i don't had idea which software i need to compile the source code to generate the binary executable under Windows environement ?
